#!/usr/bin/env python3
"""python01Example: A simple introductory example using the Python interface to the C-Core API.

This is the first example in a series. Much of the discussion here
covers the main concepts when using the RaimaDB C-Core API through
Python. Read this example first; later examples build on it and only
discuss the new concepts they introduce. Mirrors core01Example_main.c
in the C-Core *Getting Started* series (see ``examples/README.md`` for
where the C originals live in your RaimaDB installation).

The concepts introduced in this example are:

- A TFS (Transactional File Server) handle:
    - Allocating a TFS handle
    - Initializing the TFS handle
    - Dropping a database using the TFS handle
    - Freeing the TFS handle
- A database handle:
    - Allocating a database handle
    - Associating a catalog with the database handle
    - Opening the database with shared access
    - Freeing the database handle
- Transactions:
    - Starting a read transaction
    - Starting an update transaction
    - Committing a transaction
    - Rolling back a transaction
- A cursor:
    - Getting a cursor for a table
    - Moving the cursor to the first row
    - Reading a row using the cursor
- Inserting a row into a table without using a cursor

A TFS handle is used for communicating with a TFS. In some
configurations the TFS is embedded directly into the application; in
others it uses a transport to communicate with a remote TFS. The TFS
handle hides these details and is the main handle for RDM — it manages
resources and allocates database handles. We allocate one in
``do_work()``, use it, and free it.

A database handle is allocated from the TFS handle. It is used to
associate a catalog, open the database, and perform operations.

A catalog is a JSON representation of a schema — a collection of
tables and indexes in the SDL (SQL Data Definition Language) format.
The C examples generate the catalog with a separate ``rdm-compile``
tool that produces ``.h`` and ``.c`` files; the Python bindings
sidestep that step entirely. We pass the SDL source as a string
directly to ``db.setCatalog(SDL)``. In this first example the schema
has a single table ``INFO`` with a single column ``MESSAGE`` and no
indexes. The catalog is used to create a database if it does not
already exist when opening, and to validate the database against the
schema if it does.

A transaction is a sequence of operations treated as a single unit of
work — atomic, consistent, isolated, and durable. We start a read
transaction in ``read_a_row()`` and an update transaction in
``write_a_row()``. The trivial transactions in this example don't
exercise multiple tables, complex consistency logic, or transaction
handles; we'll show those in later examples.

A cursor walks rows in a table. We get one for the ``INFO`` table,
move to the first row, and read the column value via attribute access
(``cursor.MESSAGE``). Cursors in the Python bindings can also be used
as Python iterators — keep in mind that any iteration mutates cursor
position. Cursors should be freed when no longer needed, though they
are freed automatically when the database is freed.

We insert a row directly without a cursor in this example. Use cases
that need a cursor for the inserted row are shown in later examples.

A few differences worth noting between the C API and the Python
interface:

- The C API reads rows into a struct generated by ``rdm-compile``;
  the Python interface defines row classes dynamically where each
  column is exposed as an attribute.
- Tables, keys, references, and user-defined keys are referenced by
  passing their names in as uppercase strings (e.g. ``"INFO"``,
  ``"MESSAGE"``) rather than by struct/enum identifiers.
- The C API is organised into several headers. The Python interface
  mirrors that with sub-modules: ``rdm.tfsapi`` for TFS operations,
  ``rdm.dbapi`` for database operations, ``rdm.cursorapi`` for cursor
  operations, ``rdm.rdmapi`` for general RDM API, ``rdm.types`` for
  types, ``rdm.exceptions`` for exceptions, and ``rdm.retcodetypes``
  for return code types.
"""

import sys
from rdm import *
from rdm.tfsapi import *
from rdm.dbapi import *
from rdm.cursorapi import *
from rdm.rdmapi import *
from rdm.types import *
from rdm.exceptions import *
from rdm.retcodetypes import *
## [setup_code]

## Reads a row from the database and prints it.
#
# This function starts a read transaction, gets a cursor for the table,
# moves to the first row, reads the column value, and prints it.
# Param: db The database handle.
# Return: Status.Okay on success, status code otherwise.
def read_a_row(db):
    rc, trans = db.startRead()
    if rc != Status.Okay:
        print("rdm_dbStartRead failed to start a read transaction")
    else:
        rc, cursor = db.getRows("INFO")
        if rc != Status.Okay:
            print("rdm_dbGetRows failed to associate a cursor with a table")
        else:
            rc = cursor.moveToFirst()
            if rc != Status.Okay:
                print("rdm_cursorMoveToFirst failed to move to the first row in the table")
            else:
                print("The row read from the database is: {}".format(cursor.MESSAGE))
            cursor.free()
        trans.end()
    return rc

## Inserts a "Hello World!" row into the database.
#
# This function starts an update transaction, inserts a row into the table,
# commits if successful, rolls back if not.
# Param: db The database handle.
# Return: Status.Okay on success, status code otherwise.
def write_a_row(db):
    rc, trans = db.startUpdate()
    if rc == Status.Okay:
        rc, _ = db.insertRow("INFO", MESSAGE="Hello World!")
        if rc == Status.Okay:
            rc = trans.end()
            if rc != Status.Okay:
                print("rdm_dbEnd failed to commit the transaction")
        else:
            print("rdm_dbInsertRow failed to insert a row into the table")
            trans.endRollback()
    else:
        print("rdm_dbStartUpdate failed to start an update transaction")
    return rc

## Performs operations with the database handle.
#
# This function calls write_a_row and read_a_row to perform operations.
# Param: db The database handle.
# Return: Status.Okay on success, status code otherwise.
def do_work_with_db_handle(db):
    rc = write_a_row(db)
    if rc == Status.Okay:
        rc = read_a_row(db)
    return rc

## Performs operations with the database handle.
#
# This function allocates a database handle, associates the catalog,
# opens the database (creating if necessary), performs work, and frees the handle.
# Param: tfs The TFS handle.
# Return: Status.Okay on success, status code otherwise.
def do_work_with_tfs_handle(tfs):
    db = tfs.allocDatabase()
    rc = db.setCatalog("""
create table info
(
    message char(50) not null
);
""")
    if rc == Status.Okay:
        rc = db.open("python01", OpenMode.SHARED)
        if rc == Status.Okay:
            rc = do_work_with_db_handle(db)
        else:
            print("rdm_dbOpen failed to open the database 'python01'")
    else:
        print("rdm_dbSetCatalog failed to associate a catalog with the database handle")

    db.free()
    return rc

## Performs operations with the TFS handle.
#
# This function allocates and initializes a TFS handle, drops the database if exists,
# performs work with the TFS, and frees the handle.
# Return: Status.Okay on success, status code otherwise.
def do_work():
    tfs = allocTfs()
    rc = tfs.initialize()
    if rc != Status.Okay:
        print("rdm_tfsInitialize failed to initialize the TFS handle")
    else:
        try:
            tfs.dropDatabase("python01")
            print("The database was dropped")
        except ErrorNoDB:
            print("The database does not exist")

        rc = do_work_with_tfs_handle(tfs)

    tfs.free()
    return rc

## Main function for the example program.
#
# Returns 0 on success, 1 on failure. The __main__ guard wraps this in
# sys.exit() so the script's process exit code matches.
def main(argv=None):
    rc = do_work()
    return 0 if rc == Status.Okay else 1

if __name__ == "__main__":
    sys.exit(main())