#!/usr/bin/env python3
## @package: python01Example_main
# A simple introductory example using the Python interface to the C-Core API.
#
# Refer to the README file for details how to run this example.
#
# This is an introductory example using the Python interface.
# Much of the discussion in this example covers the main concepts when using
# the RaimaDb C-Core API through Python.
#
# We do not include a comprehensive list of examples using this interface.
# This is just one example to get you started. To learn more about the product,
# we recommend following the C core series of examples as they are quite
# comprehensive.
#
# This particular example is similar to the C-core example core01Example_main.c,
# except that it uses the Python interface.
#
# The concepts we are introducing in this example are:
# - A TFS (Transactional File Server) handle:
#   - Allocating a TFS handle
#   - Initializing the TFS handle
#   - Dropping a database using the TFS handle
#   - Freeing the TFS handle
# - A database handle:
#   - Allocating a database handle
#   - Associating a catalog with the database handle
#   - Opening the database with shared access
#   - Freeing the database handle
# - Transactions:
#   - Starting a read transaction
#   - Starting an update transaction
#   - Committing a transaction
#   - Rolling back a transaction
# - Cursor:
#   - Getting a cursor for a table
#   - Moving the cursor to the first row
#   - Reading a row using the cursor
# - Inserting a row into a table without using a cursor
#
# A TFS handle is used for communicating with a TFS. The TFS handle hides details about
# whether the TFS is embedded or remote. The TFS handle is also the main handle for RDM,
# managing resources and allocating database handles.
#
# A database handle is used for communicating with a database. The database handle is
# allocated using the TFS handle. The database handle is used to open a database,
# associate a catalog with the database, and perform operations on the database.
#
# A catalog is a representation of a schema which is a collection of tables and indexes
# in the SQL Data Definition Language (SDL) format. In this example, we set the catalog
# directly in the code as a string. The schema has a single table named INFO with a single
# column named MESSAGE. There are no indexes.
#
# The catalog is used to create a database if it does not exist when opening.
#
# In this example we provide the schema in the form of SQL data definition statements (SDL).
# The Python interface can also work with an existing database where the SDL has already
# been set up and we do not need to provide the SDL in the program. This is not shown in the example.
#
# A transaction is a sequence of operations treated as a single unit of work. Transactions
# ensure atomicity, consistency, and durability. In this example, we start simple read and
# update transactions without locks or advanced features.
#
# A cursor is used to read rows from a table. In this example, we get a cursor for all rows
# in the table, move to the first row, and access the column value directly.
#
# Note that cursors should be freed when no longer needed, though they are freed when the
# database is freed.
#
# It may also be worth mentioning that the cursors in our Python interface also can act as
# Python iterators. Keep in mind that any iterator on the cursor has side effects on the cursor
# objects with respect to its position.
#
# We insert a row directly without a cursor in this example.
#
# The main function calls do_work() to perform the operations.
#
# Here are some differences between the C API and the Python interface:
# - The C API reads out a row into a struct definition (that is generated by rdm-compile)
#   while in the Python interface classes are defined dynamically where we have attributes
#   to access each column.
# - The classes for our tables, keys, references, and user defined keys are not referenced
#   by their class names but rather retrieved though our API passing their names in as strings.
# - The C API is organized in a number of header files. In Python we have similarly organized
#   it into a number of sub modules. The setup includes modules like rdm.tfsapi for TFS operations,
#   rdm.dbapi for database operations, rdm.cursorapi for cursor operations, rdm.rdmapi for
#   general RDM API, rdm.types for types, rdm.exceptions for exceptions, and rdm.retcodetypes
#   or return code types.
#
# @subsection setup_section Imports
# Import the rdm package. Install with: pip install .
#
# For development, use an editable install: pip install -e .

import sys
from rdm import *
from rdm.tfsapi import *
from rdm.dbapi import *
from rdm.cursorapi import *
from rdm.rdmapi import *
from rdm.types import *
from rdm.exceptions import *
from rdm.retcodetypes import *
## [setup_code]

## Reads a row from the database and prints it.
#
# This function starts a read transaction, gets a cursor for the table,
# moves to the first row, reads the column value, and prints it.
# Param: db The database handle.
# Return: Status.Okay on success, status code otherwise.
def read_a_row(db):
    rc, trans = db.startRead()
    if rc != Status.Okay:
        print("rdm_dbStartRead failed to start a read transaction")
    else:
        rc, cursor = db.getRows("INFO")
        if rc != Status.Okay:
            print("rdm_dbGetRows failed to associate a cursor with a table")
        else:
            rc = cursor.moveToFirst()
            if rc != Status.Okay:
                print("rdm_cursorMoveToFirst failed to move to the first row in the table")
            else:
                print("The row read from the database is: {}".format(cursor.MESSAGE))
            cursor.free()
        trans.end()
    return rc

## Inserts a "Hello World!" row into the database.
#
# This function starts an update transaction, inserts a row into the table,
# commits if successful, rolls back if not.
# Param: db The database handle.
# Return: Status.Okay on success, status code otherwise.
def write_a_row(db):
    rc, trans = db.startUpdate()
    if rc == Status.Okay:
        rc, _ = db.insertRow("INFO", MESSAGE="Hello World!")
        if rc == Status.Okay:
            rc = trans.end()
            if rc != Status.Okay:
                print("rdm_dbEnd failed to commit the transaction")
        else:
            print("rdm_dbInsertRow failed to insert a row into the table")
            trans.endRollback()
    else:
        print("rdm_dbStartUpdate failed to start an update transaction")
    return rc

## Performs operations with the database handle.
#
# This function calls write_a_row and read_a_row to perform operations.
# Param: db The database handle.
# Return: Status.Okay on success, status code otherwise.
def do_work_with_db_handle(db):
    rc = write_a_row(db)
    if rc == Status.Okay:
        rc = read_a_row(db)
    return rc

## Performs operations with the database handle.
#
# This function allocates a database handle, associates the catalog,
# opens the database (creating if necessary), performs work, and frees the handle.
# Param: tfs The TFS handle.
# Return: Status.Okay on success, status code otherwise.
def do_work_with_tfs_handle(tfs):
    db = tfs.allocDatabase()
    rc = db.setCatalog("""
create table info
(
    message char(50) not null
);
""")
    if rc == Status.Okay:
        rc = db.open("python01", OpenMode.SHARED)
        if rc == Status.Okay:
            rc = do_work_with_db_handle(db)
        else:
            print("rdm_dbOpen failed to open the database 'python01'")
    else:
        print("rdm_dbSetCatalog failed to associate a catalog with the database handle")

    db.free()
    return rc

## Performs operations with the TFS handle.
#
# This function allocates and initializes a TFS handle, drops the database if exists,
# performs work with the TFS, and frees the handle.
# Return: Status.Okay on success, status code otherwise.
def do_work():
    tfs = allocTfs()
    rc = tfs.initialize()
    if rc != Status.Okay:
        print("rdm_tfsInitialize failed to initialize the TFS handle")
    else:
        try:
            tfs.dropDatabase("python01")
            print("The database was dropped")
        except ErrorNoDB:
            pass  # Database does not exist yet, nothing to drop

        rc = do_work_with_tfs_handle(tfs)

    tfs.free()
    return rc

## Main function for the example program.
#
# This function calls do_work and exits with appropriate status.
def main():
    rc = do_work()
    sys.exit(0 if rc == Status.Okay else 1)

if __name__ == "__main__":
    main()