#!/usr/bin/env python3
"""python03Example: Row IDs and foreign key columns.

Builds upon python01Example. Mirrors core03Example_main.c. Read
python01 first to familiarise yourself with the main concepts.

The concepts introduced in this example are:

- Using a SQL keyword as a table name
- Autogenerated RowID primary key columns
- Foreign key columns:
    - Inserting rows with foreign key columns
    - Inserting with the use of a returned cursor
    - Reading rows with foreign key columns
- Getting a cursor without explicit allocation
- Retrieving a Row ID value from a cursor
- Cursor navigation to a particular Row ID

The schema has two tables: ``"PRIMARY"`` and ``SECONDARY``.
``"PRIMARY"`` has two columns ``ID`` and ``INTERJECTION``. ``ID`` is
an autogenerated RowID primary key (and so cannot be null);
``INTERJECTION`` is a character string. ``SECONDARY`` has two
columns ``ID`` and ``ENTITY``: ``ID`` is a foreign key referencing
``"PRIMARY".ID`` (and *can* be null); ``ENTITY`` is a character
string. Note that ``SECONDARY``'s own row id is stored internally
and can be retrieved from a cursor via ``getRowId()``.

``PRIMARY`` is a SQL keyword and so must be quoted in the SDL. The
quoted name is case-sensitive — uppercase to match the internal
casing of unquoted table names. This follows the SQL standard;
many SQL databases default to translating unquoted names to
lowercase.

In ``insert_rows()`` we insert two ``"PRIMARY"`` rows ("Hi",
"Hello") and two ``SECONDARY`` rows ("World" referencing "Hello",
"Andromeda" referencing "Hi"). When inserting a ``"PRIMARY"`` row
we need its autogenerated row id so we can populate the foreign
key on ``SECONDARY``. ``db.insertRow()`` returns a tuple
``(Status, cursor)`` whose cursor is positioned on the just-inserted
row; ``cursor.getRowId()`` then yields the row id, which we pass as
the ``ID=`` value when inserting the matching ``SECONDARY`` row.

In ``read_some_rows()`` we use two cursors — one per table — to
read one ``SECONDARY`` row and the matching ``"PRIMARY"`` row. The
foreign key is followed by ``primary_cursor.moveToRowId(secondary.ID)``.

In the Python interface, the cursor returned from ``db.insertRow()``
removes the need for an explicit ``allocCursor()`` step; the
binding allocates the cursor and returns it for you.

"""
import sys
from rdm import *
from rdm.tfsapi import *
from rdm.dbapi import *
from rdm.cursorapi import *
from rdm.rdmapi import *
from rdm.types import *
from rdm.exceptions import *
from rdm.retcodetypes import *

SCHEMA = """
create table "PRIMARY"
(
    id rowid primary key,
    interjection char(50) not null
);

create table secondary
(
    id rowid references "PRIMARY",
    entity char(50) not null
);
"""


def read_rows(db):
    """Walk SECONDARY in primary-key order, follow the FK, print pairs."""
    rc, trans = db.startRead()
    if rc != Status.Okay:
        print("rdm_dbStartRead failed to start a read transaction")
        return rc
    rc, sec = db.getRows("SECONDARY")
    if rc != Status.Okay:
        print("rdm_dbGetRows failed to associate a cursor with SECONDARY")
        trans.end()
        return rc
    rc, prim = db.getRows("PRIMARY")
    if rc != Status.Okay:
        print("rdm_dbGetRows failed to associate a cursor with PRIMARY")
        sec.free()
        trans.end()
        return rc
    while True:
        status = sec.moveToNext()
        if status == Status.EndOfCursor:
            break
        if status != Status.Okay:
            print("rdm_cursorMoveToNext on SECONDARY failed")
            sec.free()
            prim.free()
            trans.end()
            return status
        # The FK column is `id`; follow it by row id.
        status = prim.moveToRowId(sec.ID)
        if status != Status.Okay:
            print("rdm_cursorMoveToRowId failed to follow the foreign key")
            sec.free()
            prim.free()
            trans.end()
            return status
        print("{} {}!".format(prim.INTERJECTION, sec.ENTITY))
    sec.free()
    prim.free()
    trans.end()
    return Status.Okay


def write_rows(db):
    """Insert two PRIMARY rows and two SECONDARY rows referencing them."""
    rc, trans = db.startUpdate()
    if rc != Status.Okay:
        print("rdm_dbStartUpdate failed to start an update transaction")
        return rc
    rc, hi_row = db.insertRow("PRIMARY", INTERJECTION="Hi")
    if rc != Status.Okay:
        print("Failed to insert 'Hi' into PRIMARY")
        trans.endRollback()
        return rc
    hi_id = hi_row.getRowId()
    rc, hello_row = db.insertRow("PRIMARY", INTERJECTION="Hello")
    if rc != Status.Okay:
        print("Failed to insert 'Hello' into PRIMARY")
        trans.endRollback()
        return rc
    hello_id = hello_row.getRowId()
    rc, _ = db.insertRow("SECONDARY", ID=hello_id, ENTITY="World")
    if rc != Status.Okay:
        print("Failed to insert 'World' into SECONDARY")
        trans.endRollback()
        return rc
    rc, _ = db.insertRow("SECONDARY", ID=hi_id, ENTITY="Andromeda")
    if rc != Status.Okay:
        print("Failed to insert 'Andromeda' into SECONDARY")
        trans.endRollback()
        return rc
    return trans.end()


def do_work_with_db_handle(db):
    rc = write_rows(db)
    if rc == Status.Okay:
        rc = read_rows(db)
    return rc


def do_work_with_tfs_handle(tfs):
    db = tfs.allocDatabase()
    rc = db.setCatalog(SCHEMA)
    if rc == Status.Okay:
        rc = db.open("python03", OpenMode.SHARED)
        if rc == Status.Okay:
            rc = do_work_with_db_handle(db)
        else:
            print("rdm_dbOpen failed to open the database 'python03'")
    else:
        print("rdm_dbSetCatalog failed to associate a catalog with the database handle")
    db.free()
    return rc


def do_work():
    tfs = allocTfs()
    rc = tfs.initialize()
    if rc != Status.Okay:
        print("rdm_tfsInitialize failed to initialize the TFS handle")
        tfs.free()
        return rc
    try:
        tfs.dropDatabase("python03")
        print("The database was dropped")
    except ErrorNoDB:
        print("The database does not exist")
    rc = do_work_with_tfs_handle(tfs)
    tfs.free()
    return rc


def main(argv=None):
    return 0 if do_work() == Status.Okay else 1


if __name__ == "__main__":
    sys.exit(main())
