# cython: language_level=3

# String constants corresponding to the macros
STR_TFS_TYPE_EMBED = "EMBED"
STR_TFS_TYPE_SERVER = "SERVER"
STR_TFS_TYPE_CLIENT = "CLIENT"
STR_TFS_TYPE_REMOTE = "REMOTE"
STR_TFS_TYPE_HYBRID = "HYBRID"
STR_TFS_TYPE_DEFAULT = "DEFAULT"
STR_TFS_TYPE_RDM = "RDM"
STR_TFS_TYPE_LOCAL = "LOCAL"